DROP TABLE IF EXISTS `approval_expense`;
CREATE TABLE `approval_expense` (
  `id` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '报销单号: EXP+YYYYMMDD+序号',
  `applicant_id` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '报销人ID',
  `department_id` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '部门ID',
  `type` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '报销类型',
  `amount` decimal(10,2) NOT NULL COMMENT '总金额',
  `reason` text COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '报销事由',
  `apply_date` date NOT NULL COMMENT '申请日期',
  `expense_date` date NOT NULL COMMENT '费用发生日期',
  `status` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'draft' COMMENT '状态',
  `dept_approver_id` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '部门审批人ID',
  `dept_approver_name` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '部门审批人姓名',
  `dept_approval_status` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '部门审批状态',
  `dept_approval_opinion` text COLLATE utf8mb4_unicode_ci COMMENT '部门审批意见',
  `dept_approval_time` datetime DEFAULT NULL COMMENT '部门审批时间',
  `finance_approver_id` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '财务审批人ID',
  `finance_approver_name` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '财务审批人姓名',
  `finance_approval_status` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '财务审批状态',
  `finance_approval_opinion` text COLLATE utf8mb4_unicode_ci COMMENT '财务审批意见',
  `finance_approval_time` datetime DEFAULT NULL COMMENT '财务审批时间',
  `payment_date` date DEFAULT NULL COMMENT '打款时间',
  `payment_proof` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '打款凭证URL',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted_at` datetime DEFAULT NULL COMMENT '删除时间',
  PRIMARY KEY (`id`),
  KEY `idx_expense_applicant` (`applicant_id`),
  KEY `idx_expense_department` (`department_id`),
  KEY `idx_expense_status` (`status`),
  KEY `idx_expense_apply_date` (`apply_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='费用报销单表';
