DROP TABLE IF EXISTS `biz_asset`;
CREATE TABLE `biz_asset` (
  `id` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '资产编号(格式: ASSET+序号)',
  `name` varchar(200) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '资产名称',
  `category` enum('electronic','furniture','book','other') COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '资产类别',
  `brand_model` varchar(200) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '品牌/型号',
  `purchase_date` date NOT NULL COMMENT '购置日期',
  `purchase_price` decimal(10,2) NOT NULL COMMENT '购置金额(元)',
  `current_value` decimal(10,2) DEFAULT NULL COMMENT '当前价值',
  `status` enum('stock','in_use','borrowed','maintenance','scrapped') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'stock' COMMENT '资产状态',
  `user_id` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '使用人ID',
  `location` varchar(200) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '存放位置',
  `borrow_date` date DEFAULT NULL COMMENT '借出日期',
  `expected_return_date` date DEFAULT NULL COMMENT '预计归还日期',
  `actual_return_date` date DEFAULT NULL COMMENT '实际归还日期',
  `maintenance_record` json DEFAULT NULL COMMENT '维护记录',
  `images` json DEFAULT NULL COMMENT '资产图片URL数组',
  `notes` text COLLATE utf8mb4_unicode_ci COMMENT '备注信息',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `created_by` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '创建人ID',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `updated_by` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '更新人ID',
  `is_deleted` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否删除',
  `deleted_at` datetime DEFAULT NULL COMMENT '删除时间',
  `deleted_by` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '删除人ID',
  `version` int NOT NULL DEFAULT '0' COMMENT '乐观锁版本号',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='资产信息表';
