DROP TABLE IF EXISTS `sys_employee`;
CREATE TABLE `sys_employee` (
  `id` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '员工编号(格式: EMP+YYYYMMDD+序号)',
  `name` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '姓名',
  `english_name` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '英文名',
  `gender` enum('male','female') COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '性别',
  `birth_date` date DEFAULT NULL COMMENT '出生日期',
  `phone` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '联系电话',
  `email` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '邮箱',
  `avatar` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '头像URL',
  `department_id` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '部门ID',
  `position` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '职位',
  `level` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '职级',
  `manager_id` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '直属上级ID',
  `join_date` date NOT NULL COMMENT '入职日期',
  `probation_status` enum('probation','regular','resigned') COLLATE utf8mb4_unicode_ci DEFAULT 'regular' COMMENT '试用期状态',
  `probation_end_date` date DEFAULT NULL COMMENT '试用期结束日期',
  `work_years` int DEFAULT '0' COMMENT '工龄(年)',
  `status` enum('active','resigned','suspended') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'active' COMMENT '员工状态',
  `office_location` varchar(200) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '办公位置',
  `emergency_contact` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '紧急联系人',
  `emergency_phone` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '紧急联系电话',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `created_by` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '创建人ID',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `updated_by` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '更新人ID',
  `is_deleted` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否删除(0否1是)',
  `deleted_at` datetime DEFAULT NULL COMMENT '删除时间',
  `deleted_by` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '删除人ID',
  `version` int NOT NULL DEFAULT '0' COMMENT '乐观锁版本号',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='员工信息表';
