-- 数据字典项表
CREATE TABLE `sys_dict_item` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `dict_type_id` bigint NOT NULL COMMENT '字典类型ID',
  `dict_type_code` varchar(50) NOT NULL COMMENT '字典类型编码',
  `type_code` varchar(50) NOT NULL COMMENT '类型编码',
  `label` varchar(100) NOT NULL COMMENT '字典标签',
  `value` varchar(200) NOT NULL COMMENT '字典值',
  `color_type` varchar(20) DEFAULT NULL COMMENT '颜色类型（primary/success/warning/danger等）',
  `color` varchar(50) DEFAULT NULL COMMENT '自定义颜色',
  `icon` varchar(100) DEFAULT NULL COMMENT '图标',
  `sort_order` int NOT NULL DEFAULT '0' COMMENT '排序顺序',
  `sort` int NOT NULL DEFAULT '0' COMMENT '排序号',
  `status` varchar(20) NOT NULL DEFAULT 'enabled' COMMENT '状态：enabled-启用，disabled-禁用',
  `ext_props` json DEFAULT NULL COMMENT '扩展属性（JSON格式）',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `created_by` bigint DEFAULT NULL COMMENT '创建人ID',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人ID',
  `is_deleted` tinyint NOT NULL DEFAULT '0' COMMENT '是否删除：0-未删除，1-已删除',
  `deleted_at` datetime DEFAULT NULL COMMENT '删除时间',
  `deleted_by` bigint DEFAULT NULL COMMENT '删除人ID',
  PRIMARY KEY (`id`),
  KEY `idx_dict_type_id` (`dict_type_id`),
  KEY `idx_dict_type_code` (`dict_type_code`),
  KEY `idx_type_code` (`type_code`),
  KEY `idx_status` (`status`),
  KEY `idx_sort` (`sort`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='数据字典项表';
