-- 数据字典类型表
CREATE TABLE `sys_dict_type` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `code` varchar(50) NOT NULL COMMENT '字典类型编码',
  `name` varchar(100) NOT NULL COMMENT '字典类型名称',
  `description` varchar(500) DEFAULT NULL COMMENT '描述',
  `category` varchar(50) NOT NULL DEFAULT 'system' COMMENT '分类：system-系统，business-业务',
  `status` varchar(20) NOT NULL DEFAULT 'enabled' COMMENT '状态：enabled-启用，disabled-禁用',
  `item_count` int NOT NULL DEFAULT '0' COMMENT '字典项数量',
  `sort_order` int NOT NULL DEFAULT '0' COMMENT '排序顺序',
  `ext_props` json DEFAULT NULL COMMENT '扩展属性（JSON格式）',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  `sort` int NOT NULL DEFAULT '0' COMMENT '排序号',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `created_by` bigint DEFAULT NULL COMMENT '创建人ID',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人ID',
  `is_deleted` tinyint NOT NULL DEFAULT '0' COMMENT '是否删除：0-未删除，1-已删除',
  `deleted_at` datetime DEFAULT NULL COMMENT '删除时间',
  `deleted_by` bigint DEFAULT NULL COMMENT '删除人ID',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_code` (`code`),
  KEY `idx_category` (`category`),
  KEY `idx_status` (`status`),
  KEY `idx_sort` (`sort`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='数据字典类型表';
